de-commenting initChecks job

diff --git a/.github/workflows/k8s-apply.yaml b/.github/workflows/k8s-apply.yaml
--- a/.github/workflows/k8s-apply.yaml
+++ b/.github/workflows/k8s-apply.yaml
@@ -62,36 +62,35 @@ jobs:
         run: |
           set -euo pipefail
 
-          exit 0
-          # TEAMS_LIST=$(echo $TEAMS | tr "," "\n")
+          TEAMS_LIST=$(echo $TEAMS | tr "," "\n")
 
-          # CHECK_SUCCESS=0
+          CHECK_SUCCESS=0
 
-          # for TEAM in $TEAMS_LIST; do
-          #   set +e
-          #   # Check current user membership with gh api 
-          #   echo "Check if user is member of $TEAM"           
-          #   GH_TEAM_MEMBERSHIP_RESPONSE=$(gh api -i --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \/orgs/$ORG/teams/$TEAM/memberships/$USER)
-          #   set -e
+          for TEAM in $TEAMS_LIST; do
+            set +e
+            # Check current user membership with gh api 
+            echo "Check if user is member of $TEAM"           
+            GH_TEAM_MEMBERSHIP_RESPONSE=$(gh api -i --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \/orgs/$ORG/teams/$TEAM/memberships/$USER)
+            set -e
             
-          #   # Extract the HTTP status code
-          #   HTTP_CODE=$(echo $GH_TEAM_MEMBERSHIP_RESPONSE | head -n 1 | cut -d' ' -f 2)
+            # Extract the HTTP status code
+            HTTP_CODE=$(echo $GH_TEAM_MEMBERSHIP_RESPONSE | head -n 1 | cut -d' ' -f 2)
 
-          #   if [[ $HTTP_CODE -eq 200 ]]; then
-          #     echo "User is member of $TEAM"
-          #     CHECK_SUCCESS=1
-          #     break
-          #   else
-          #     echo "User is NOT member of $TEAM"
-          #   fi
-          # done
+            if [[ $HTTP_CODE -eq 200 ]]; then
+              echo "User is member of $TEAM"
+              CHECK_SUCCESS=1
+              break
+            else
+              echo "User is NOT member of $TEAM"
+            fi
+          done
             
-          # if [[ $CHECK_SUCCESS -eq 0 ]]; then
-          #   echo "::error:: Resource not found. Please check the organization ($ORG), team ($TEAMS), and username ($USER). $USER is not memeber of specified teams."
-          #   exit 1
-          # fi
+          if [[ $CHECK_SUCCESS -eq 0 ]]; then
+            echo "::error:: Resource not found. Please check the organization ($ORG), team ($TEAMS), and username ($USER). $USER is not memeber of specified teams."
+            exit 1
+          fi
 
-          # echo "$USER has the correct permissions to execute the workflow."
+          echo "$USER has the correct permissions to execute the workflow."
 
   create_runner:
     name: Create Self-Hosted Runner
@@ -140,7 +139,7 @@ jobs:
     with:
       environment: ${{ inputs.environment }}
       timeout_seconds: 300
-      
+
   delete_runner:
     name: Delete Self-Hosted Runner
     needs: [create_runner, deploy, tf_apply_secrets]
