feat: update helm scripts references (#7)

diff --git a/.github/workflows/k8s-apply-sub.yaml b/.github/workflows/k8s-apply-sub.yaml
--- a/.github/workflows/k8s-apply-sub.yaml
+++ b/.github/workflows/k8s-apply-sub.yaml
@@ -22,11 +22,43 @@ defaults:
     shell: bash
 
 env:
-  SCRIPTS_FOLDER: "./scripts"
+  SCRIPTS_FOLDER: "./interop-infra-commons/scripts/helm"
 
 jobs:
+  initChecks:
+    runs-on: ubuntu-22.04
+    environment: ${{ inputs.environment }}
+    steps:
+      - name: Check user is a ${{ vars.ALLOWED_DEPLOY_GH_TEAM }} team member
+        id: checkUserPermissions
+        if: ${{ inputs.environment != 'dev' }}
+        env:
+            GITHUB_TOKEN: ${{ secrets.BOT_TEAMS_RO_PAT }}
+            ORG: ${{ github.repository_owner }}
+            TEAM: ${{ vars.ALLOWED_DEPLOY_GH_TEAM }}
+            USER: ${{ github.triggering_actor	}}
+        run: |
+          set -euo pipefail
+          set +e
+          # Check current user membership with gh api
+          GH_TEAM_MEMBERSHIP_RESPONSE=$(gh api -i --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \/orgs/$ORG/teams/$TEAM/memberships/$USER)
+          set -e
+          
+          # Extract the HTTP status code
+          HTTP_CODE=$(echo $GH_TEAM_MEMBERSHIP_RESPONSE | head -n 1 | cut -d' ' -f 2)
+          if [[ $HTTP_CODE -eq 404 ]]; then
+            echo "::error:: Resource not found. Please check the organization ($ORG), team ($TEAM), and user names ($USER). $USER is not memeber of specified team."
+            exit 1
+          elif [[ $HTTP_CODE -ne 200 ]]; then
+            echo "::error:: API response status code $HTTP_CODE."
+            echo $GH_TEAM_MEMBERSHIP_RESPONSE | tail -n 1 | jq -r .
+            exit 1
+          fi
+          echo "$USER has the correct permissions to execute the workflow."
+
   workflow_setup:
     name: Setup steps
+    needs: [ initChecks ]
     runs-on: [ self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}" ]
     environment: ${{ inputs.environment }}
     env:
@@ -86,6 +118,18 @@ jobs:
       - name: Checkout
         id: checkout
         uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
+
+      - name: Checkout scripts repository
+        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
+        with:
+          repository: pagopa/interop-infra-commons
+          path: interop-infra-commons 
+          fetch-depth: 0
+          sparse-checkout: 'scripts/helm'
+          #token: ${{ secrets.PRIVATE_REPOS_PAT }}
+          ssh-key: ${{ secrets.PRIVATE_REPOS_SSH_KEY }}
+          ref: ${{ vars.INFRA_COMMONS_TAG }}
+          
       - name: Set kubeconfig
         run: |
           aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
@@ -97,6 +141,7 @@ jobs:
         run: |
           set -euo pipefail
 
+          export PROJECT_DIR=$(pwd)
           $SCRIPTS_FOLDER/kubectlApply-svc-single-standalone.sh --debug --environment $K8S_NAMESPACE -m $MICROSERVICE_NAME --output console 
 
           CURRENT_SVC=$(kubectl get deployments -n $K8S_NAMESPACE | awk '{if (NR!=1) print $1}' | grep -v grep | grep -i $MICROSERVICE_NAME) 
@@ -141,6 +186,18 @@ jobs:
       - name: Checkout
         id: checkout
         uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
+
+      - name: Checkout scripts repository
+        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
+        with:
+          repository: pagopa/interop-infra-commons
+          path: interop-infra-commons 
+          fetch-depth: 0
+          sparse-checkout: 'scripts/helm'
+          #token: ${{ secrets.PRIVATE_REPOS_PAT }}
+          ssh-key: ${{ secrets.PRIVATE_REPOS_SSH_KEY }}
+          ref: ${{ vars.INFRA_COMMONS_TAG }}
+
       - name: Set kubeconfig
         run: |
           aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
@@ -151,4 +208,5 @@ jobs:
         run: |
           set -euo pipefail
 
+          export PROJECT_DIR=$(pwd)
           $SCRIPTS_FOLDER/kubectlApply-cron-single-standalone.sh --debug --environment $K8S_NAMESPACE -j $CRONJOB_NAME --output console 
