align w/ latest wf updates

diff --git a/.github/workflows/k8s-apply-sub.yaml b/.github/workflows/k8s-apply-sub.yaml
--- a/.github/workflows/k8s-apply-sub.yaml
+++ b/.github/workflows/k8s-apply-sub.yaml
@@ -17,6 +17,7 @@ on:
       EKS_CLUSTER_NAME:
         required: true
 
+  
 defaults:
   run:
     shell: bash
@@ -40,7 +41,9 @@ jobs:
         run: |
           set -euo pipefail
           TEAMS_LIST=$(echo $TEAMS | tr "," "\n")
+
           CHECK_SUCCESS=0
+
           for TEAM in $TEAMS_LIST; do
             set +e
             # Check current user membership with gh api 
@@ -50,6 +53,7 @@ jobs:
             
             # Extract the HTTP status code
             HTTP_CODE=$(echo $GH_TEAM_MEMBERSHIP_RESPONSE | head -n 1 | cut -d' ' -f 2)
+
             if [[ $HTTP_CODE -eq 200 ]]; then
               echo "User is member of $TEAM"
               CHECK_SUCCESS=1
@@ -63,8 +67,8 @@ jobs:
             echo "::error:: Resource not found. Please check the organization ($ORG), team ($TEAMS), and username ($USER). $USER is not memeber of specified teams."
             exit 1
           fi
-          echo "$USER has the correct permissions to execute the workflow."
 
+          echo "$USER has the correct permissions to execute the workflow."
   workflow_setup:
     name: Setup steps
     needs: [ initChecks ]
@@ -140,6 +144,29 @@ jobs:
       - name: Set kubeconfig
         run: |
           aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
+      - name: Kubectl Diff
+        id: kubectl_diff
+        env: 
+          MICROSERVICE_NAME: ${{ matrix.microservice }}
+        run: |
+          set -euo pipefail
+
+          set +e
+          export PROJECT_DIR=$(pwd)
+
+          $SCRIPTS_FOLDER/kubectlDiff-svc-single-standalone.sh --environment ${{ inputs.environment }} --microservice $MICROSERVICE_NAME -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml --output console
+
+          DIFF_EXIT_CODE=$?
+          set -e
+          
+          if [[ $DIFF_EXIT_CODE == 0 ]]; then
+            echo "Diff Output: No diff has been found for ${MICROSERVICE_NAME}"
+          elif [[ $DIFF_EXIT_CODE == 1 ]]; then
+            echo "Diff Output: Diff has been found for ${MICROSERVICE_NAME}"
+          else
+            echo "::error title=Diff Error::Error occurred during diff, exit code $DIFF_EXIT_CODE"
+            exit $DIFF_EXIT_CODE
+          fi
       - name: Deploy
         env:
           MICROSERVICE_NAME: ${{ matrix.microservice }}
@@ -209,6 +236,28 @@ jobs:
       - name: Set kubeconfig
         run: |
           aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
+      - name: Kubectl Diff
+        id: kubectl_diff
+        env: 
+          CRONJOB_NAME: ${{ matrix.cronjob }}
+        run: |
+          set -euo pipefail
+
+          export PROJECT_DIR=$(pwd)
+
+          set +e
+          $SCRIPTS_FOLDER/kubectlDiff-cron-single-standalone.sh --environment ${{ inputs.environment }} --job $CRONJOB_NAME -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml --output console
+          DIFF_EXIT_CODE=$?
+          set -e
+          
+          if [[ $DIFF_EXIT_CODE == 0 ]]; then
+            echo "Diff Output: No diff has been found for ${CRONJOB_NAME}"
+          elif [[ $DIFF_EXIT_CODE == 1 ]]; then
+            echo "Diff Output: Diff has been found for ${CRONJOB_NAME}"
+          else
+            echo "::error title=Diff Error::Error occurred during diff, exit code $DIFF_EXIT_CODE"
+            exit $DIFF_EXIT_CODE
+          fi
       - name: Deploy
         env:
           CRONJOB_NAME: ${{ matrix.cronjob }}
